### ISSUE TITLE
Test miss match with list of TimeZone Id

### ISSUE THREAD

**Issue by guitarrapc** [PowerShell/xTimeZone#20]
Description
----

Get-TimeZone should not use Get-CimInstance but should use .NET.

Effect
----

This problem should be occur with all non-English Language settings and happen after 1.4.0.0, which release is start using .NET.

Detail of problem
----

As README shows, xTimezone's ```TimeZone``` property expects result of ```[System.TimeZoneInfo]::GetSystemTimeZones().Id```. This is set with P/Invoke in https://github.com/PowerShell/xTimeZone/blob/dev/DSCResources/SetTimeZone.cs#L233.

However ```Test-TargetResource``` is not checking with same way but using CIM Instance Method https://github.com/PowerShell/xTimeZone/blob/dev/DSCResources/TimezoneHelper.psm1#L42-L44. Unfortunately CIM Instance not return same value of TimeZone which expect in Set but it returns Localized Name.

Reproduce
----

You can reproduce this issue with none English Language Windows Server 2012 R2. ex. Japanese. Both WMF4 and 5 will see issue.

Below Configuration will set Time zone to ```Tokyo Standard Time``` perfectly but always fail Test.

```powershell
configuration ServiceWin32Time
{
    Import-DSCResource -ModuleName xTimeZone;
    
    Node localhost
    {
        xTimeZone TokyoStandard
        {
            TimeZone = "Tokyo Standard Time"
            IsSingleInstance = "YES"
        }
    }
}
```

The result of ```(Get-CimInstance -ClassName WIN32_Timezone -Namespace root\cimv2).StandardName``` that Get-TimeZone function is using returns TimeZoneStandardName ```東京 (標準時)```, while TimeZone property expect to compare with TimeZoneId ```Tokyo Standard Time```.

How to resolve
----

The issue is easy well known Localization problem for Timezone. 
http://stackoverflow.com/questions/31796766/how-to-get-utc-timezone-displayname-net-4-0

You just need to convert StandardName, that CIM returns, to Id which you use to SET Timezone. Below is ```Get-TimeZoneId``` function to convert CIM result StandardName to Id. You can figure out what is the TimeZone Id from this function.

```powershell
function Get-TimeZoneId
{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [System.String]
        $TimeZone
    )
    
    # Convert TimeZone Standard Name to TimeZone Id
    $timeZoneInfo = [System.TimeZoneInfo]::GetSystemTimeZones() | Where-Object StandardName -eq $TimeZone
    return $timeZoneInfo.Id
}
```

Now you can Test TimeZoneId with ```Test-TimeZone``` function.

```powershell
function Test-TimeZone
{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [System.String]
        $ExpectTimeZoneId
    )
    
    # Test Expected Id is same as Current Id
    $currentId = Get-TimeZoneId -TimeZone (Get-TimeZone)
    return $ExpectTimeZoneId -eq $currentId
}
```

Here's new Get-TargetResource and Test-TargetResource.

```powershell
function Get-TargetResource
{
    [CmdletBinding()]
    [OutputType([Hashtable])]
    param
    (
        [parameter(Mandatory = $true)]
        [ValidateSet('Yes')]
        [String]
        $IsSingleInstance,

        [parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [String]
        $TimeZone
    )

    #Get the current TimeZone
    $CurrentTimeZone = Get-TimeZoneId -TimeZone (Get-TimeZone)

    $returnValue = @{
        TimeZone = $CurrentTimeZone
        IsSingleInstance = 'Yes'
    }

    #Output the target resource
    $returnValue
}
```

```powershell
function Test-TargetResource
{
    [CmdletBinding()]
    [OutputType([Boolean])]
    param
    (
        [parameter(Mandatory = $true)]
        [ValidateSet('Yes')]
        [String]
        $IsSingleInstance, 

        [parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [String]
        $TimeZone
    )
    return Test-TimeZone -ExpectTimeZoneId $TimeZone
}
```

Issue will fix with this change.

**Comment by PlagueHO** [comment]
Hi @guitarrapc  - that is some good information and great issue reporting there! Do you want to submit a PR with the change?

**Comment by guitarrapc** [comment]
Hi, I think this change requires Test but I don't have much time to implement Pester series. I can PR, if only add new functions is allows.

**Comment by PlagueHO** [comment]
Hi @guitarrapc - all good. I can use your code and submit a PR with it and include updates to the tests if you like?

**Comment by guitarrapc** [comment]
Hi @PlagueHO 
Thanks, it's much appreciated. I've created PR for you. Please review it.

**Comment by guitarrapc** [comment]
PR merged! Appreciate @PlagueHO .

Let's close issue.
