### ISSUE TITLE
Failed to install with Install-Module

### ISSUE THREAD

**Issue by MasashiTeruya** [PowerShell/xTimeZone#26]
Failed to install because xTimeZone is overriding existing Get-TargetResource and so on. I think we should not export DSC functions in psd1 file unless there is specific reason.
# Logs
```
PS C:\> Install-Module xTimeZone -Scope CurrentUser
PackageManagement\Install-Package : A command with name 'Get-TargetResource' is already available on this system. This
module 'xTimeZone' may override the existing commands. If you still want to install this module 'xTimeZone', use -Allow
Clobber parameter.
発生場所 C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1661 文字:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package]、E
    xception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage

```

# Environment
Windows 10 build 1607
Name                           Value
----                           -----
PSVersion                      5.1.14393.82
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.82
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by kwirkykat** [comment]
@MasashiTeruya Fixed in this [commit](https://github.com/PowerShell/xTimeZone/pull/27/commits/1c7f3a0efcee00d29789f48c6567b27aa645a78d) and updated for the 1.6.0.0 release
