### ISSUE TITLE
Incorporate changes from robwi repo

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/xTimeZone#28]
Additions have been made to this module in a separate repo:
[https://github.com/robwi/xTimeZone](https://github.com/robwi/xTimeZone)

HELP WANTED

If someone would like to review this work and incorporate changes back to the resource kit as a new PR, that would be a great project.

**Comment by PlagueHO** [comment]
Hi @mgreenegit - this looks like an old version of [xTimeZone](https://github.com/PowerShell/xTimeZone) resource already in the resource kit. I did a scan through and couldn't determine the new features- although I could be being completely blind and missing the obvious (not the first time :grin:)

**Comment by mgreenegit** [comment]
Thanks @PlagueHO for taking the time to review the module..  I will close out the issue and communicate this back to @robwi so he can close out the repo.  This is a really big help!
